name: my_movie
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.0
  dio: ^5.5.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  flutter_rating_bar: ^4.0.1
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.6
  webview_flutter_wkwebview: ^3.14.0 
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  equatable: ^2.0.5
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  fl_chart: ^0.68.0
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  flutter_secure_storage: ^9.2.2
  firebase_app_check: ^0.3.0+4
  html_unescape: ^2.0.0
  

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/background.jpg
    - assets/images/dark_background.jpg
    - assets/images/background_2.jpg
    - assets/images/background_3.jpg
    - assets/images/dark_background_2.jpg
    - assets/images/thegodfather.jpg
    - assets/images/placeholder.png
    - assets/images/category.png
    - assets/images/actor.png
    - assets/images/dice.png
    - assets/images/dice_1.png
    - assets/images/dice_2.png
    - assets/images/dice_3.png
    - assets/images/dice_4.png
    - assets/images/dice_5.png
    - assets/images/dice_6.png
    - assets/images/quizz.png
    - assets/images/man.png
    - assets/logos/logo.png
    - assets/icons/dark_mode.svg
    - assets/icons/light_mode.svg
  
