// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR7oo_HcJjjgK01oboqPAjcBevLs3yQzc',
    appId: '1:661273203018:ios:b86589652a7b4d4a8731b3',
    messagingSenderId: '661273203018',
    projectId: 'flutter-movie-app-9eb63',
    storageBucket: 'flutter-movie-app-9eb63.appspot.com',
    iosBundleId: 'com.example.myMovie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWqW1cZUfpXVQDpZYkvvp0eobaEfPL5o4',
    appId: '1:661273203018:web:5fd4aa26becdb72c8731b3',
    messagingSenderId: '661273203018',
    projectId: 'flutter-movie-app-9eb63',
    authDomain: 'flutter-movie-app-9eb63.firebaseapp.com',
    storageBucket: 'flutter-movie-app-9eb63.appspot.com',
    measurementId: 'G-HC23XHHFNM',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWqW1cZUfpXVQDpZYkvvp0eobaEfPL5o4',
    appId: '1:661273203018:web:5fd4aa26becdb72c8731b3',
    messagingSenderId: '661273203018',
    projectId: 'flutter-movie-app-9eb63',
    authDomain: 'flutter-movie-app-9eb63.firebaseapp.com',
    storageBucket: 'flutter-movie-app-9eb63.appspot.com',
    measurementId: 'G-HC23XHHFNM',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR7oo_HcJjjgK01oboqPAjcBevLs3yQzc',
    appId: '1:661273203018:ios:b86589652a7b4d4a8731b3',
    messagingSenderId: '661273203018',
    projectId: 'flutter-movie-app-9eb63',
    storageBucket: 'flutter-movie-app-9eb63.appspot.com',
    iosBundleId: 'com.example.myMovie',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUNEg8MSy-Y-OTqdQxE1bWpL4l-N_84oc',
    appId: '1:661273203018:android:c85e0a3f4dbc7fd28731b3',
    messagingSenderId: '661273203018',
    projectId: 'flutter-movie-app-9eb63',
    storageBucket: 'flutter-movie-app-9eb63.appspot.com',
  );

}